### ISSUE TITLE
Should be an OR not AND ;)

### ISSUE THREAD

**Issue by razvn** [joshlong/bootiful-spring-boot-3#1]
https://github.com/joshlong/bootiful-spring-boot-3/blob/b34ebcabc07b91eb71e4145901aba23b9c864fff/service/src/main/java/com/example/service/ServiceApplication.java#L49

`if (name == null || !Character.isUpperCase(name.charAt(0)))`

**Comment by joshlong** [comment]
hah! thank you for this :) ive only just seen this PR but the code has, accidentally, been fixed so thank you for that.
